- hosts: "{{ host }}"
  vars_prompt:
    - name: type1
      prompt: "Enter format "
      private: no
    - name: dev1
      prompt: "Enter device name "
      private: no

  tasks:
    - filesystem:
        fstype: "{{type1}}"
        dev: ext4
        resizefs: yes
        force: yes
