- hosts: all
  #remote_user: 'ec2-user'
  #become: True
  tasks:
    - package:
        name: "{{ service }}"
        state: present
    - service:
        name: "{{ service }}"
        state: "{{ states }}"

