- hosts: localhost
  tasks:
       - pip:
             name: docker-py
             state: present
       - docker_container:
             name: "mydocker"
             state: present
             image: "centos"
            
              


