- hosts: localhost
  tasks:
         - pip:
             name: boto3
             state: present
         - ec2:
             key_name: "aws1"
             instance_type: "t2.micro"
             image: "ami-5b673c34"
             wait: yes
             group: "launch-wizard-2"
             count: 1
             vpc_subnet_id: "subnet-a0f875ec"
             assign_public_ip: yes
             instance_ids: "i-012fcad85adecd2f4"
             region: ap-south-1

             aws_access_key: "AKIAJY3WRWCCEHA5SLXA"
             aws_secret_key: "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"
