- hosts: localhost
  vars_prompt:
            - name: username
              prompt: "enter username"
               
            - name: password
              prompt: "enter password"
                
            - name: groupname
              prompt: "enter  gropuname"
  tasks:  
      - name: add a user with a group
        user: 
               name: "{{username}}"
               password: "{{password}}"
               state: present
               shell: "/bin/bash"
               group: "{{groupname}}"
