- hosts: 192.168.43.238
  vars_prompt:
        - name: master_ip
          prompt: "enter master ip to configure"
  tasks:
        
       - name: copy file jdk software
         copy:
                src: "/root/Desktop/jdk-8u171-linux-x64.rpm"
                dest: "/root/Desktop"
       - name: copy hadoop file rpm software
         copy: 
                src: "/root/Desktop/hadoop-1.2.1-1.x86_64.rpm"
                dest: "/root/Desktop"
        
       - name: command for install the jdk software
         package: 
                name: /root/Desktop/jdk-8u171-linux-x64.rpm
                state: present

       - name: for setting path of jdk software and permanent it 
         lineinfile: 
                path: /root/.bashrc
                line: "export JAVA_HOME=/usr/java/jdk-8u171-linux-x64.rpm"
                create: yes
               
       - name: file entry permanent
         lineinfile:
                path: /root/.bashrc
                line: "export PATH=/usr/java/jdk-8u171-linux-x64.rpm/bin/:/usr/java/jdk-8u171-linux-x64.rpm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin"
                create: yes 
                

       - name: for installing hadoop software
         package: 
                name: /root/Desktop/hadoop-1.2.1-1.x86_64.rpm
                state: present
      # - name: entry of data file
       #  command: mkdir /name
      
       - name: configure some data node file
         copy:
                src: "/root/r.txt"
                dest: "/etc/hadoop/hdfs-site.xml"

       - name: copy 
         template: 
                src: "/etc/hadoop/core-site.xml"
                dest: "/etc/hadoop/core-site.xml"
       - name: taking report of your slave/data node
         command: "hadoop namenode -format"

       
                  
       - name: start your master  for having part of hadoop cluster
         command: "hadoop-daemon.sh start namenode"

       - name: Disable your firewall for disable security
         command: "iptables -F"
       
       - name: check your data node start or not
         command: "jps"
       - name: taking report of your datanodes
         command: "hadoop  dfsadmin  -report" 

 

        
