- hosts: all
  tasks:
  
	  docker:
	    name: myapplication
	    image: centos
	    state: reloaded
	    pull: always
	    devices:
	    - "/dev/sda:/dev/xvda:rwm"
	    ports:
	    - "8080:9000"
	    - "127.0.0.1:8081:9001/udp"
	    extra_hosts:
	      host1: "192.168.0.1"
	      host2: "192.168.0.2"
	    env:
	      SECRET_KEY: ssssh

