- hosts: all
  tasks:
    -  package:
        name: "httpd"
        state: present
    -  copy:
        src: "/var/www/html/"
        dest: "/var/www/html/"
    -  service:
        name: "httpd"
        state: started
    -  firewalld:
        permanent: true
        state: disabled
